### ISSUE TITLE
The named manifest is not known to the registry

### ISSUE THREAD

**Issue by gjsjohnmurray** [rcemper/Wsock-Embedded-Py#2]
```
> docker-compose build
Building iris
Step 1/13 : ARG IMAGE=containers.intersystems.com/intersystems/iris-ml:2020.3.0.304.0
Step 2/13 : FROM $IMAGE
ERROR: Service 'iris' failed to build : manifest for containers.intersystems.com/intersystems/iris-ml:2020.3.0.304.0 not found: manifest unknown: The named manifest is not known to the registry.
```

**Comment by gjsjohnmurray** [comment]
Line 1 of Dockerfile needs to be:
```
ARG IMAGE=containers.intersystems.com/intersystems/iris-ml-community:2020.3.0.304.0
```

**Comment by rcemper** [comment]
Thank you John!

|ARG 
IMAGE=containers.intersystems.com/intersystems/iris-ml-community:2020.3.0.304.0 
This was the image I was asking for 6 weeks ago! |

|And got the pointer 4 seeks ago to the other imga thas has no licnese 
and ... , and ... ,and .... The 2 related hints I added to READ.ME are 
now obsolete:|**

*docker image*: if you don't have the required image already you need to 
download it from containers.intersystems.com

|docker login -u="<username>" -p="<passwd>" containers.intersystems.com 
docker pull 
containers.intersystems.com/intersystems/iris-ml:2020.3.0.304.0 |

*
iris.key:*The container has no license included. You may use it as 
single user or provide your own container license key.

|Makes my work and the example easier! Best regards, Robert |

Am 08.02.2021 um 12:50 schrieb John Murray:

**Comment by rcemper** [comment]
There is a new container + zpm + embedded py since a few days
ARG IMAGE=intersystemsdc/iris-ml-community:2020.3.0.302.0-zpm

Best regards, Robert

Am 08.02.2021 um 15:25 schrieb R.Cemper:

**Comment by gjsjohnmurray** [comment]
Thanks for fixing this in 0.0.2
